# Generated by Django 4.2.5 on 2023-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
