# Generated by Django 4.2.5 on 2024-01-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_create_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='birthday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
